# Site settings
title:          Nestor Bermudez
description:    "Where I explain and rant about things"
url:            "https://nbermudezs.github.io"

# Author
author:
  name:         Nestor Bermudez
  url:          http://nbermudezs.com
  email:        nestor.bermudezs@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5


theme_skin: black # blue turquoise green berry orange ceramic


# Profile information
name: Nestor Bermudez
tagline: Problem solver
pic: profile@2x.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Hey there! I'm Nestor and I like to think of myself as a problem solver.
Former Math Olympiad participant and coder since I was 15. Doing software engineering professionally since 2013.
Passionate about challenges and delivering with quality.
Competitive and eager to learn. Strong communication skills, both verbal and written.
Proven track record of successfully delivering results in fast paced companies.<br/>
I'm now a graduate student at University of Illinois at Urbana-Champaign working with <a href='http://shj.cs.illinois.edu/' target='_blank'>Prof. Sheldon H. Jacobson</a> on
stochastic optimization and, like everyone these days, on AI and data analytics."

# Sidebar links
email: nestor.bermudezs@gmail.com
# emailEdu: nab6@illinois.edu
phone: +1 (217) 721 2899
# website: nbermudezs.com #do not add http://
linkedin: nbermudezs
github: nbermudezs
twitter: '@nbermudezs'
instagram: nbermudezs
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
